import { Conversation, Customer, Message, User, WhatsAppGroup } from '../types';

export const USERS_STORAGE_KEY = 'realizzetravel_users';

export function loadStoredUsers(): User[] {
  if (typeof window === 'undefined') return [...DEMO_USERS];
  try {
    const raw = localStorage.getItem(USERS_STORAGE_KEY);
    if (!raw) return [...DEMO_USERS];
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return parsed;
    }
  } catch {
    // fallback to demo users
  }
  return [...DEMO_USERS];
}

export function saveStoredUsers(users: User[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(USERS_STORAGE_KEY, JSON.stringify(users));
  } catch (e) {
    console.warn('Falha ao salvar usuários no localStorage', e);
  }
}

export const DEMO_USERS: User[] = [
  {
    id: 'usr_admin',
    organization_id: 'org_realizzetravel',
    name: 'Carlos Santos (Administrador)',
    email: 'admin@realizzetravel.com.br',
    role: 'ADMIN',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_supervisor',
    organization_id: 'org_realizzetravel',
    name: 'Renata Lima (Supervisora)',
    email: 'supervisor@realizzetravel.com.br',
    role: 'SUPERVISOR',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_joao',
    organization_id: 'org_realizzetravel',
    name: 'Consultor 1 (João Silva)',
    email: 'consultor1@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_maria',
    organization_id: 'org_realizzetravel',
    name: 'Consultor 2 (Maria Oliveira)',
    email: 'consultor2@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_pedro',
    organization_id: 'org_realizzetravel',
    name: 'Consultor 3 (Pedro Souza)',
    email: 'consultor3@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_anapaula',
    organization_id: 'org_realizzetravel',
    name: 'Consultor 4 (Ana Paula)',
    email: 'consultor4@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_lucas',
    organization_id: 'org_realizzetravel',
    name: 'Consultor 5 (Lucas Ferreira)',
    email: 'consultor5@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_beatriz',
    organization_id: 'org_realizzetravel',
    name: 'Consultor 6 (Beatriz Costa)',
    email: 'consultor6@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust_matheus',
    organization_id: 'org_realizzetravel',
    name: 'Matheus Primo',
    phone: '558185057129',
    email: 'matheus.primo@gmail.com',
    destination_interest: 'Maragogi & Porto de Galinhas (Resort All Inclusive)',
    travel_date: '2026-11-15',
    passenger_count: 2,
    budget: 'R$ 7.500',
    created_at: new Date(Date.now() - 3600 * 2000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cust_camila',
    organization_id: 'org_realizzetravel',
    name: 'Camila Albuquerque',
    phone: '5511984124433',
    email: 'camila.albuquerque@hotmail.com',
    destination_interest: 'Orlando & Disney (Família)',
    travel_date: '2026-07-10',
    passenger_count: 4,
    budget: 'R$ 32.000',
    created_at: new Date(Date.now() - 3600 * 5000).toISOString(),
    updated_at: new Date(Date.now() - 1800 * 1000).toISOString(),
  },
  {
    id: 'cust_rodrigo',
    organization_id: 'org_realizzetravel',
    name: 'Rodrigo Mendes',
    phone: '5521971238890',
    email: 'rodrigo.mendes@uol.com.br',
    destination_interest: 'Gramado & Canela (Lua de Mel)',
    travel_date: '2026-08-20',
    passenger_count: 2,
    budget: 'R$ 6.000',
    created_at: new Date(Date.now() - 3600 * 8000).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000).toISOString(),
  },
  {
    id: 'cust_juliana',
    organization_id: 'org_realizzetravel',
    name: 'Juliana Rocha',
    phone: '5531998761122',
    email: 'juliana.rocha@yahoo.com.br',
    destination_interest: 'Buenos Aires & Bariloche (Neve)',
    travel_date: '2026-09-05',
    passenger_count: 2,
    budget: 'R$ 11.000',
    created_at: new Date(Date.now() - 3600 * 12000).toISOString(),
    updated_at: new Date(Date.now() - 7200 * 1000).toISOString(),
  },
  {
    id: 'cust_gabriel',
    organization_id: 'org_realizzetravel',
    name: 'Gabriel Torres',
    phone: '5581992345566',
    email: 'gabriel.torres@gmail.com',
    destination_interest: 'Fernando de Noronha (Mergulho & Passeios)',
    travel_date: '2026-10-12',
    passenger_count: 2,
    budget: 'R$ 9.800',
    created_at: new Date(Date.now() - 3600 * 15000).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 4000).toISOString(),
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_matheus',
    organization_id: 'org_realizzetravel',
    customer_id: 'cust_matheus',
    status: 'OPEN',
    assigned_user_id: 'usr_admin',
    assigned_user: DEMO_USERS[0],
    priority: 'HIGH',
    created_at: new Date(Date.now() - 3600 * 2000).toISOString(),
    updated_at: new Date().toISOString(),
    last_message_at: new Date().toISOString(),
    auto_requeued_inactivity: false,
    customer: DEMO_CUSTOMERS[0],
    reminder_date: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    reminder_note: 'Retornar após conversa com a esposa sobre as datas',
    reminder_status: 'PENDING',
    last_message: {
      id: 'msg_matheus_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_matheus',
      sender_name: 'Matheus Primo',
      message_type: 'text',
      content: 'Perfeito! Vou conversar com a minha esposa hoje à noite e já te confirmo as datas para fechar.',
      status: 'delivered',
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
  },
  {
    id: 'conv_camila',
    organization_id: 'org_realizzetravel',
    customer_id: 'cust_camila',
    status: 'OPEN',
    assigned_user_id: 'usr_joao',
    assigned_user: DEMO_USERS[2],
    priority: 'HIGH',
    created_at: new Date(Date.now() - 3600 * 5000).toISOString(),
    updated_at: new Date(Date.now() - 1800 * 1000).toISOString(),
    last_message_at: new Date(Date.now() - 1800 * 1000).toISOString(),
    auto_requeued_inactivity: false,
    customer: DEMO_CUSTOMERS[1],
    last_message: {
      id: 'msg_camila_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_camila',
      sender_type: 'AGENT',
      sender_id: 'usr_joao',
      sender_name: 'Consultor 1 (João Silva)',
      message_type: 'text',
      content: '*[Consultor 1]*: Montei 3 opções de ingressos Disney + Universal com hospedagem dentro do complexo. Segue o PDF com o comparativo detalhado!',
      status: 'delivered',
      created_at: new Date(Date.now() - 1800 * 1000).toISOString(),
    },
  },
  {
    id: 'conv_rodrigo',
    organization_id: 'org_realizzetravel',
    customer_id: 'cust_rodrigo',
    status: 'WAITING',
    assigned_user_id: null,
    priority: 'MEDIUM',
    created_at: new Date(Date.now() - 3600 * 8000).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    last_message_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    auto_requeued_inactivity: false,
    customer: DEMO_CUSTOMERS[2],
    last_message: {
      id: 'msg_rodrigo_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_rodrigo',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_rodrigo',
      sender_name: 'Rodrigo Mendes',
      message_type: 'text',
      content: 'Boa tarde! Gostaria de um orçamento para pacote de Lua de Mel em Gramado no mês de Agosto, para 2 pessoas.',
      status: 'delivered',
      created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    },
  },
  {
    id: 'conv_juliana',
    organization_id: 'org_realizzetravel',
    customer_id: 'cust_juliana',
    status: 'OPEN',
    assigned_user_id: 'usr_maria',
    assigned_user: DEMO_USERS[3],
    priority: 'MEDIUM',
    created_at: new Date(Date.now() - 3600 * 12000).toISOString(),
    updated_at: new Date(Date.now() - 7200 * 1000).toISOString(),
    last_message_at: new Date(Date.now() - 7200 * 1000).toISOString(),
    auto_requeued_inactivity: false,
    customer: DEMO_CUSTOMERS[3],
    reminder_date: new Date().toISOString().split('T')[0], // Today
    reminder_note: 'Cartão vai virar hoje (dia 20) - Ligar para fechar pacote Bariloche',
    reminder_status: 'PENDING',
    last_message: {
      id: 'msg_juliana_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_juliana',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_juliana',
      sender_name: 'Juliana Rocha',
      message_type: 'text',
      content: 'Vocês conseguem incluir o passeio no Cerro Catedral com aula de esqui no pacote?',
      status: 'delivered',
      created_at: new Date(Date.now() - 7200 * 1000).toISOString(),
    },
  },
  {
    id: 'conv_gabriel',
    organization_id: 'org_realizzetravel',
    customer_id: 'cust_gabriel',
    status: 'WAITING',
    assigned_user_id: null,
    priority: 'MEDIUM',
    created_at: new Date(Date.now() - 3600 * 15000).toISOString(),
    updated_at: new Date(Date.now() - 3600 * 4000).toISOString(),
    last_message_at: new Date(Date.now() - 3600 * 4000).toISOString(),
    auto_requeued_inactivity: false,
    customer: DEMO_CUSTOMERS[4],
    last_message: {
      id: 'msg_gabriel_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_gabriel',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_gabriel',
      sender_name: 'Gabriel Torres',
      message_type: 'text',
      content: 'Olá Realizze! Quero planejar uma viagem de 5 dias em Noronha em Outubro. Vocês já emitem as taxas ambientais junto com aéreo e pousada?',
      status: 'delivered',
      created_at: new Date(Date.now() - 3600 * 4000).toISOString(),
    },
  },
];

export const DEMO_MESSAGES: Record<string, Message[]> = {
  conv_matheus: [
    {
      id: 'm_mat_1',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_matheus',
      sender_name: 'Matheus Primo',
      message_type: 'text',
      content: 'Olá! Gostaria de atendimento com a Realizze Travel para minha viagem.',
      status: 'delivered',
      created_at: new Date(Date.now() - 3600 * 2000).toISOString(),
    },
    {
      id: 'm_mat_2',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'AGENT',
      sender_id: 'usr_admin',
      sender_name: 'Carlos Santos (Administrador)',
      message_type: 'text',
      content: '*[Carlos Santos]*: Olá Matheus! Tudo bem? Sou consultor da Realizze Travel. Vai ser um prazer planejar seu roteiro. Para onde você está pensando em viajar e quantas pessoas vão com você?',
      status: 'delivered',
      created_at: new Date(Date.now() - 3500 * 2000).toISOString(),
    },
    {
      id: 'm_mat_3',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_matheus',
      sender_name: 'Matheus Primo',
      message_type: 'text',
      content: 'Estamos pensando em ir para Maragogi ou Porto de Galinhas em Novembro, seríamos eu e minha esposa (2 pessoas). Queríamos um resort All Inclusive bem relaxante!',
      status: 'delivered',
      created_at: new Date(Date.now() - 3400 * 2000).toISOString(),
    },
    {
      id: 'm_mat_4',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'AGENT',
      sender_id: 'usr_admin',
      sender_name: 'Carlos Santos (Administrador)',
      message_type: 'text',
      content: '*[Carlos Santos]*: Excelente escolha! Novembro é maravilhoso para o litoral nordestino, mar calmo com piscinas naturais cristalinas. Temos tarifas exclusivas com o Salinas Maragogi e com o Grand Oca.',
      status: 'delivered',
      created_at: new Date(Date.now() - 3300 * 2000).toISOString(),
    },
    {
      id: 'm_mat_5',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_matheus',
      sender_name: 'Matheus Primo',
      message_type: 'text',
      content: 'Que ótimo! Qual o valor aproximado para 5 noites com voo saindo de Recife ou capitais próximas e transfer incluso?',
      status: 'delivered',
      created_at: new Date(Date.now() - 3200 * 2000).toISOString(),
    },
    {
      id: 'm_mat_6',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'AGENT',
      sender_id: 'usr_admin',
      sender_name: 'Carlos Santos (Administrador)',
      message_type: 'text',
      content: '*[Carlos Santos]*: Conseguimos o pacote completo (5 diárias All Inclusive + Transfer privativo + Seguro Viagem) por R$ 7.290 para o casal, parcelado em até 10x sem juros no cartão ou com 5% de desconto à vista via Pix!',
      status: 'delivered',
      created_at: new Date(Date.now() - 1200 * 1000).toISOString(),
    },
    {
      id: 'msg_matheus_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_matheus',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_matheus',
      sender_name: 'Matheus Primo',
      message_type: 'text',
      content: 'Perfeito! Vou conversar com a minha esposa hoje à noite e já te confirmo as datas para fechar.',
      status: 'delivered',
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
  ],
  conv_camila: [
    {
      id: 'm_cam_1',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_camila',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_camila',
      sender_name: 'Camila Albuquerque',
      message_type: 'text',
      content: 'Oi! Gostaria de cotar uma viagem para Orlando com minha família em Julho/2026. Somos 2 adultos e 2 crianças (8 e 12 anos).',
      status: 'delivered',
      created_at: new Date(Date.now() - 3600 * 5000).toISOString(),
    },
    {
      id: 'm_cam_2',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_camila',
      sender_type: 'AGENT',
      sender_id: 'usr_joao',
      sender_name: 'Consultor 1 (João Silva)',
      message_type: 'text',
      content: '*[Consultor 1]*: Olá Camila! Tudo bem? Vai ser incrível essa viagem! Julho é a temporada de férias e temos opções fantásticas de hotéis parceiros Disney com transfer gratuito para os parques.',
      status: 'delivered',
      created_at: new Date(Date.now() - 3500 * 5000).toISOString(),
    },
    {
      id: 'm_cam_3',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_camila',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_camila',
      sender_name: 'Camila Albuquerque',
      message_type: 'text',
      content: 'Queremos 10 dias de viagem, com visita aos 4 parques temáticos da Disney e os 2 da Universal!',
      status: 'delivered',
      created_at: new Date(Date.now() - 3000 * 5000).toISOString(),
    },
    {
      id: 'msg_camila_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_camila',
      sender_type: 'AGENT',
      sender_id: 'usr_joao',
      sender_name: 'Consultor 1 (João Silva)',
      message_type: 'text',
      content: '*[Consultor 1]*: Montei 3 opções de ingressos Disney + Universal com hospedagem dentro do complexo. Segue o PDF com o comparativo detalhado!',
      status: 'delivered',
      created_at: new Date(Date.now() - 1800 * 1000).toISOString(),
    },
  ],
  conv_rodrigo: [
    {
      id: 'msg_rodrigo_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_rodrigo',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_rodrigo',
      sender_name: 'Rodrigo Mendes',
      message_type: 'text',
      content: 'Boa tarde! Gostaria de um orçamento para pacote de Lua de Mel em Gramado no mês de Agosto, para 2 pessoas.',
      status: 'delivered',
      created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    },
  ],
  conv_juliana: [
    {
      id: 'm_jul_1',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_juliana',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_juliana',
      sender_name: 'Juliana Rocha',
      message_type: 'text',
      content: 'Boa tarde! Estamos planejando uma viagem para ver neve em Bariloche combinando com alguns dias em Buenos Aires em Setembro.',
      status: 'delivered',
      created_at: new Date(Date.now() - 3600 * 12000).toISOString(),
    },
    {
      id: 'm_jul_2',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_juliana',
      sender_type: 'AGENT',
      sender_id: 'usr_maria',
      sender_name: 'Consultor 2 (Maria Oliveira)',
      message_type: 'text',
      content: '*[Consultor 2]*: Olá Juliana! Maravilha! Esse roteiro combinado Buenos Aires (3 noites) + Bariloche (4 noites) é um dos nossos campeões de elogios.',
      status: 'delivered',
      created_at: new Date(Date.now() - 3500 * 12000).toISOString(),
    },
    {
      id: 'msg_juliana_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_juliana',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_juliana',
      sender_name: 'Juliana Rocha',
      message_type: 'text',
      content: 'Vocês conseguem incluir o passeio no Cerro Catedral com aula de esqui no pacote?',
      status: 'delivered',
      created_at: new Date(Date.now() - 7200 * 1000).toISOString(),
    },
  ],
  conv_gabriel: [
    {
      id: 'msg_gabriel_last',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_gabriel',
      sender_type: 'CUSTOMER',
      sender_id: 'cust_gabriel',
      sender_name: 'Gabriel Torres',
      message_type: 'text',
      content: 'Olá Realizze! Quero planejar uma viagem de 5 dias em Noronha em Outubro. Vocês já emitem as taxas ambientais junto com aéreo e pousada?',
      status: 'delivered',
      created_at: new Date(Date.now() - 3600 * 4000).toISOString(),
    },
  ],
};

export const DEMO_WHATSAPP_GROUPS: WhatsAppGroup[] = [];

