import { Conversation, Customer, Message, User } from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr_admin',
    organization_id: 'org_realizzetravel',
    name: 'Carlos Santos',
    email: 'admin@realizzetravel.com.br',
    role: 'ADMIN',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_supervisor',
    organization_id: 'org_realizzetravel',
    name: 'Renata Lima',
    email: 'supervisor@realizzetravel.com.br',
    role: 'SUPERVISOR',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_joao',
    organization_id: 'org_realizzetravel',
    name: 'João Silva',
    email: 'joao@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_maria',
    organization_id: 'org_realizzetravel',
    name: 'Maria Oliveira',
    email: 'maria@realizzetravel.com.br',
    role: 'AGENT',
    status: 'ONLINE',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
  {
    id: 'usr_pedro',
    organization_id: 'org_realizzetravel',
    name: 'Pedro Souza',
    email: 'pedro@realizzetravel.com.br',
    role: 'AGENT',
    status: 'OFFLINE',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&h=120&fit=crop&crop=face',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    last_seen_at: new Date().toISOString(),
  },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cst_1',
    organization_id: 'org_realizzetravel',
    name: 'Carlos Alberto Ferreira',
    phone: '+55 11 98765-4321',
    email: 'carlos.alberto@email.com',
    notes: 'Interesse em pacote com tudo incluído para casal e 1 criança',
    destination_interest: 'Porto Seguro, BA',
    travel_date: '2026-11-15',
    passenger_count: 3,
    budget: 'R$ 6.500',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cst_2',
    organization_id: 'org_realizzetravel',
    name: 'Fernanda Souza Brandão',
    phone: '+55 21 99876-5432',
    email: 'fernanda.souza@email.com',
    notes: 'Procura voo direto saindo do Galeão no período matutino',
    destination_interest: 'Recife, PE',
    travel_date: '2026-10-08',
    passenger_count: 2,
    budget: 'R$ 3.200',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cst_3',
    organization_id: 'org_realizzetravel',
    name: 'Rodrigo Mendes Teixeira',
    phone: '+55 31 98765-1234',
    email: 'rodrigo.mendes@email.com',
    notes: 'Cruzeiro de Réveillon pela costa brasileira com varanda',
    destination_interest: 'Cruzeiro Costa / MSC',
    travel_date: '2026-12-28',
    passenger_count: 2,
    budget: 'R$ 14.000',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cst_4',
    organization_id: 'org_realizzetravel',
    name: 'Juliana Paes Vasconcelos',
    phone: '+55 41 97654-3210',
    email: 'juliana.paes@email.com',
    notes: 'Resort com piscina aquecida e atrações infantis',
    destination_interest: 'Gramado & Canela, RS',
    travel_date: '2026-09-20',
    passenger_count: 4,
    budget: 'R$ 8.900',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cst_5',
    organization_id: 'org_realizzetravel',
    name: 'Lucas Moura Barbosa',
    phone: '+55 61 98123-4567',
    email: 'lucas.moura@email.com',
    notes: 'Ingressos parques Disney + Universal e hospedagem em Kissimmee',
    destination_interest: 'Orlando, EUA',
    travel_date: '2027-01-10',
    passenger_count: 3,
    budget: 'R$ 28.000',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cst_6',
    organization_id: 'org_realizzetravel',
    name: 'Camila Queiroz Antunes',
    phone: '+55 71 99234-5678',
    email: 'camila.queiroz@email.com',
    notes: 'Transfer privativo aeroporto para Praia do Forte',
    destination_interest: 'Salvador e Litoral Norte, BA',
    travel_date: '2026-10-02',
    passenger_count: 2,
    budget: 'R$ 1.800',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    organization_id: 'org_realizzetravel',
    customer_id: 'cst_1',
    assigned_user_id: null,
    status: 'WAITING',
    priority: 'HIGH',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    closed_at: null,
    closed_by_user_id: null,
    last_message_at: new Date().toISOString(),
    customer: DEMO_CUSTOMERS[0],
    assigned_user: null,
    unread_count: 2,
    last_message: {
      id: 'msg_1',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_1',
      sender_type: 'CUSTOMER',
      sender_id: 'cst_1',
      message_type: 'text',
      content: 'Boa tarde! Gostaria de uma cotação para Porto Seguro em novembro com aéreo saindo de SP.',
      created_at: new Date(Date.now() - 15 * 60000).toISOString(),
      status: 'read',
    },
  },
  {
    id: 'conv_2',
    organization_id: 'org_realizzetravel',
    customer_id: 'cst_2',
    assigned_user_id: 'usr_joao',
    status: 'OPEN',
    priority: 'MEDIUM',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    closed_at: null,
    closed_by_user_id: null,
    last_message_at: new Date(Date.now() - 5 * 60000).toISOString(),
    customer: DEMO_CUSTOMERS[1],
    assigned_user: DEMO_USERS[2],
    unread_count: 0,
    last_message: {
      id: 'msg_22',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_2',
      sender_type: 'AGENT',
      sender_id: 'usr_joao',
      message_type: 'text',
      content: 'Perfeito, Fernanda! Já localizei o voo da Azul saindo às 08h30. Posso reservar os assentos?',
      created_at: new Date(Date.now() - 5 * 60000).toISOString(),
      status: 'delivered',
    },
  },
  {
    id: 'conv_3',
    organization_id: 'org_realizzetravel',
    customer_id: 'cst_3',
    assigned_user_id: null,
    status: 'WAITING',
    priority: 'URGENT',
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    closed_at: null,
    closed_by_user_id: null,
    last_message_at: new Date(Date.now() - 2 * 60000).toISOString(),
    customer: DEMO_CUSTOMERS[2],
    assigned_user: null,
    unread_count: 1,
    last_message: {
      id: 'msg_31',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_3',
      sender_type: 'CUSTOMER',
      sender_id: 'cst_3',
      message_type: 'text',
      content: 'Tem alguma cabine com varanda ainda disponível para o Réveillon? Preciso fechar hoje.',
      created_at: new Date(Date.now() - 2 * 60000).toISOString(),
      status: 'read',
    },
  },
  {
    id: 'conv_4',
    organization_id: 'org_realizzetravel',
    customer_id: 'cst_4',
    assigned_user_id: 'usr_maria',
    status: 'OPEN',
    priority: 'MEDIUM',
    created_at: new Date(Date.now() - 120 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    closed_at: null,
    closed_by_user_id: null,
    last_message_at: new Date(Date.now() - 12 * 60000).toISOString(),
    customer: DEMO_CUSTOMERS[3],
    assigned_user: DEMO_USERS[3],
    unread_count: 0,
    last_message: {
      id: 'msg_41',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_4',
      sender_type: 'AGENT',
      sender_id: 'usr_maria',
      message_type: 'text',
      content: 'Excelente, Juliana! O Hotel Alpestre aceita parcelamento em até 10x sem juros.',
      created_at: new Date(Date.now() - 12 * 60000).toISOString(),
      status: 'delivered',
    },
  },
  {
    id: 'conv_5',
    organization_id: 'org_realizzetravel',
    customer_id: 'cst_5',
    assigned_user_id: 'usr_admin',
    status: 'CLOSED',
    priority: 'HIGH',
    created_at: new Date(Date.now() - 300 * 60000).toISOString(),
    updated_at: new Date().toISOString(),
    closed_at: new Date(Date.now() - 30 * 60000).toISOString(),
    closed_by_user_id: 'usr_admin',
    last_message_at: new Date(Date.now() - 30 * 60000).toISOString(),
    customer: DEMO_CUSTOMERS[4],
    assigned_user: DEMO_USERS[0],
    unread_count: 0,
    last_message: {
      id: 'msg_51',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_5',
      sender_type: 'AGENT',
      sender_id: 'usr_admin',
      message_type: 'text',
      content: 'Vouchers e ingressos emitidos com sucesso! Boa viagem para a família!',
      created_at: new Date(Date.now() - 30 * 60000).toISOString(),
      status: 'read',
    },
  },
];

export const DEMO_MESSAGES: Record<string, Message[]> = {
  conv_1: [
    {
      id: 'msg_1',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_1',
      sender_type: 'CUSTOMER',
      sender_id: 'cst_1',
      message_type: 'text',
      content: 'Boa tarde! Gostaria de uma cotação para Porto Seguro em novembro com aéreo saindo de SP.',
      created_at: new Date(Date.now() - 15 * 60000).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_2',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_1',
      sender_type: 'SYSTEM',
      sender_id: 'system',
      message_type: 'text',
      content: 'Olá Carlos Alberto! Bem-vindo à RealizzeTravel Viagens. Nossa equipe já recebeu sua mensagem e em instantes um de nossos consultores especialistas em pacotes turísticos irá atendê-lo.',
      created_at: new Date(Date.now() - 14 * 60000).toISOString(),
      status: 'delivered',
    },
  ],
  conv_2: [
    {
      id: 'msg_20',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_2',
      sender_type: 'CUSTOMER',
      sender_id: 'cst_2',
      message_type: 'text',
      content: 'Olá! Estou pesquisando passagens para Recife no início de outubro.',
      created_at: new Date(Date.now() - 40 * 60000).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_21',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_2',
      sender_type: 'AGENT',
      sender_id: 'usr_joao',
      message_type: 'text',
      content: 'Olá Fernanda! Me chamo João Silva, consultor da RealizzeTravel. Temos ótimas tarifas promocionais para Recife saindo do Rio.',
      created_at: new Date(Date.now() - 35 * 60000).toISOString(),
      status: 'read',
    },
    {
      id: 'msg_22',
      organization_id: 'org_realizzetravel',
      conversation_id: 'conv_2',
      sender_type: 'AGENT',
      sender_id: 'usr_joao',
      message_type: 'text',
      content: 'Perfeito, Fernanda! Já localizei o voo da Azul saindo às 08h30. Posso reservar os assentos?',
      created_at: new Date(Date.now() - 5 * 60000).toISOString(),
      status: 'delivered',
    },
  ],
};
